version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pg-inventory
    restart: always
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"   # optional if you want host access
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # schema.sql will auto-run on first boot

  mcp:
    build: .
    container_name: mcp-bom-db
    depends_on:
      - db
    environment:
      # Service name 'db' resolves inside the Docker network
      DATABASE_URL: postgresql+psycopg://inventory_user:supersecret@db:5432/inventory_db
    # MCP servers need stdio (-i) if Claude runs them
    stdin_open: true
    tty: false
    # If you want to expose as a long-running service (optional)
    # ports:
    #   - "8000:8000"

volumes:
  pg_data: